version: '2'
services:
    onlinerrealtpages-app:
        image: onlinerrealtpages
        external_links:
            - onlinerrealtpages-mysql:mysql
            - onlinerrealtpages-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/onlinerrealtpages?useUnicode=true&characterEncoding=utf8&useSSL=false
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    onlinerrealtpages-mysql:
        extends:
            file: mysql.yml
            service: onlinerrealtpages-mysql
    onlinerrealtpages-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: onlinerrealtpages-elasticsearch
